### ISSUE TITLE
Notification token generation error still exists

### ISSUE THREAD

**Issue by TarangGarlapally** [TarangGarlapally/scribblebow#13]
## Notification token is not getting generated for new users or new devices.

* Tried logging into my own account from another device
* Tried creating a new account 

### Notification token is not getting generated and is giving the following error:

![image](https://user-images.githubusercontent.com/46964780/107039265-a8133400-67e3-11eb-993a-3527f7cd35ae.png)

Please look into this @karthik193

**Comment by TarangGarlapally** [comment]
Solved. It's an issue with **Brave** Browser

**Comment by karthik193** [comment]
okay
